[package]
name = "derive_ot"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
ot = { path = "../ot" }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
